export const ERROR_DETAIL = {
  // COMMON ERROR
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // DB 관련 에러
  ALREADY_EXIST: 'ALREADY_EXIST',
  ALREADY_EXIST_EMAIL: 'ALREADY_EXIST_EMAIL',
  ALREADY_EXIST_NICKNAME: 'ALREADY_EXIST_NICKNAME',
  ALREADY_EXIST_PHONE: 'ALREADY_EXIST_PHONE',

  // 인증 관련 에러
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WRONG_PASSWORD: 'WRONG_PASSWORD',

  // 서버 가용치 한계점을 넘어서는 요청이 들어왔을 때
  RUST_PANIC: 'RUST_PANIC',

  NOT_EXIST: 'NOT_EXIST',
  NOT_ENOUGH_REQ_DATA: 'NOT_ENOUGH_REQ_DATA',
  NOT_MATCH: 'NOT_MATCH',
  NOT_ALLOWED: 'NOT_ALLOWED',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  NOT_VALID: 'NOT_VALID',
  NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',

  // 요청이 구현되지 않았을 때
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',

  NOT_FOUND: 'NOT_FOUND',
  NOT_ALLOWED_METHOD: 'NOT_ALLOWED_METHOD',
  NOT_ALLOWED_HEADER: 'NOT_ALLOWED_HEADER',
  NOT_ALLOWED_QUERY: 'NOT_ALLOWED_QUERY',
  NOT_ALLOWED_BODY: 'NOT_ALLOWED_BODY',
  NOT_ALLOWED_PARAM: 'NOT_ALLOWED_PARAM',
  NOT_ALLOWED_COOKIE: 'NOT_ALLOWED_COOKIE',
  NOT_ALLOWED_FILE: 'NOT_ALLOWED_FILE',
  NOT_ALLOWED_REQUEST: 'NOT_ALLOWED_REQUEST',
  NOT_ALLOWED_RESPONSE: 'NOT_ALLOWED_RESPONSE',
  NOT_ALLOWED_STATUS: 'NOT_ALLOWED_STATUS',
  NOT_ALLOWED_CONTENT_TYPE: 'NOT_ALLOWED_CONTENT_TYPE',
  NOT_ALLOWED_CONTENT_LENGTH: 'NOT_ALLOWED_CONTENT_LENGTH',
  NOT_ALLOWED_CONTENT_ENCODING: 'NOT_ALLOWED_CONTENT_ENCODING',
  NOT_ALLOWED_CONTENT_LANGUAGE: 'NOT_ALLOWED_CONTENT_LANGUAGE',
  NOT_ALLOWED_CONTENT_LOCATION: 'NOT_ALLOWED_CONTENT_LOCATION',
  NOT_ALLOWED_CONTENT_RANGE: 'NOT_ALLOWED_CONTENT_RANGE',
  NOT_ALLOWED_CONTENT_MD5: 'NOT_ALLOWED_CONTENT_MD5',
  NOT_ALLOWED_CONTENT_DISPOSITION: 'NOT_ALLOWED_CONTENT_DISPOSITION',
  NOT_ALLOWED_CONTENT_TRANSFER_ENCODING:
    'NOT_ALLOWED_CONTENT_TRANSFER_ENCODING',
} as const;
