export const HINT_MESSAGE = {
  CHECK_INPUT_DATA: 'CHECK_INPUT_DATA',

  PLEASE_SIGNUP: 'PLEASE_SIGNUP',
  PLEASE_LOGIN: 'PLEASE_LOGIN',
  PLEASE_AGREE_TERMS: 'PLEASE_AGREE_TERMS',

  PLEASE_CHECK_EMAIL: 'PLEASE_CHECK_EMAIL',
  PLEASE_CHECK_PASSWORD: 'PLEASE_CHECK_PASSWORD',
  PLEASE_CHECK_NICKNAME: 'PLEASE_CHECK_NICKNAME',
  PLEASE_CHECK_PHONE: 'PLEASE_CHECK_PHONE',
  PLEASE_CHECK_BIRTHDAY: 'PLEASE_CHECK_BIRTHDAY',

  PLEASE_LOGIN_WITH_OTHER_ACCOUNT: 'PLEASE_LOGIN_WITH_OTHER_ACCOUNT',

  PLEASE_CHECK_TITLE: 'PLEASE_CHECK_TITLE',
  PLEASE_CHECK_CONTENT: 'PLEASE_CHECK_CONTENT',
} as const;
