export const OrderStatus = {
  CREATED: 'CREATED',
  REQUESTED: 'REQUESTED',
  CANCELED: 'CANCELED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMEOUT',
} as const;
